CREATE TABLE IF NOT EXISTS chat_memory (
    memory_id   VARCHAR(64) NOT NULL COMMENT '会话 ID',
    messages    LONGTEXT   NOT NULL COMMENT '消息列表 JSON',
    update_time DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (memory_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT 'AI 会话记忆';
